apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-projetodevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-projetodevops
  template:
    metadata:
      labels:
        app: backend-projetodevops
    spec:
      containers:
        - name: backend-projetodevops
          image: fabioaugusto2403/backend-projetodevops
          ports:
            - containerPort: 8000
