apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: backend-projetodevops
  newName: fabioaugusto2403/backend-projetodevops
  newTag: 098529b15b9bdedc94c12fcd1f1d3f41a1618020
